### PR TITLE
Upgrade io-ts to ^2.0.0, fp-ts to ^2.0.2, typescript to ^3.5.3

### LINKED ISSUE #13: Update io-ts and fp-ts dependencies to 2.x.x
io-ts and fp-ts libraries have released 2.0.x versions. Current versions of the package prevent updating io-ts due to dependency to old io-ts versions.

### PR DESCRIPTION
**Pull request by beerose**
Closes https://github.com/OliverJAsh/io-ts-reporters/issues/13

### CODE REVIEW

**Comment by beerose** [comment]
Ping @OliverJAsh

**Comment by OliverJAsh** [comment]
Sorry I've been on holiday, will get to this ASAP

**Comment by OliverJAsh** [comment]
[Released as v1.0.0](https://github.com/OliverJAsh/io-ts-reporters/releases/tag/v1.0.0)

**Comment by beerose** [comment]
Thanks! 🎉

**Pull request merged**
